const images = {
    fotoEkspetasi: require('../assets/img/foto-ekpetasi.png'),
    close: require('../assets/img/close.svg'),
    toggleNav: require('../assets/img/toggle-nav.svg'),
    fotoJurusan: require('../assets/img/foto-jurusan.png'),
    fotoJurusanTkj : require('../assets/img/foto-jurusan-tkj.png'),
    redDots: require('../assets/img/red-dots.png'),
    greenDots: require('../assets/img/green-dots.png'),
    blueDots: require('../assets/img/blue-dots.png'),
    jumbotronVideo: require('../assets/vid/jumbotron-video.mp4'),
    siswa: require('../assets/img/siswa.png'),
    more: require('../assets/img/more.svg'),
    fotoJurusanJumbotron: require('../assets/img/foto-jurusan-jumbotron.png'),
    fotoSiswa: require('../assets/img/foto-siswa.png'),
    home: require('../assets/img/home.svg'),
    fotoKesanPesan: require('../assets/img/pesan-kesan.png'),
    heart: require('../assets/img/heart.svg'),
    heartActive: require('../assets/img/heart-active.svg'),
    share: require('../assets/img/share.svg'),
    arrLeft: require('../assets/img/arrow-left.svg'),
    arrRight: require('../assets/img/arrow-right.svg'),
    // fotoKomen: require('../assets/img/foto-komen.svg'),
    iconLove: require('../assets/img/icon-love.svg'),
    iconShare: require('../assets/img/icon-share.svg'),
    fotoKomen: require('../assets/img/foto-komen.png'),
    videoThumb: require('../assets/img/video-min.png'),
    video: require('../assets/vid/jumbotron-video.mp4'),
};

export default images;